# Generated by Django 4.2.30 on 2026-08-30 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PhishingScan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("session_id", models.CharField(db_index=True, max_length=64)),
                ("content_hash", models.CharField(blank=True, max_length=64)),
                ("is_phishing", models.BooleanField(blank=True, null=True)),
                ("confidence", models.FloatField(blank=True, null=True)),
                (
                    "risk_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        max_length=16,
                    ),
                ),
                ("signals", models.JSONField(default=list)),
                ("explanation", models.TextField(blank=True)),
                ("url", models.URLField(blank=True, max_length=2000)),
                ("signed_verdict", models.TextField(blank=True)),
                ("public_key_pem", models.TextField(blank=True)),
                ("processing_time_ms", models.FloatField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Phishing Scan",
                "ordering": ["-created_at"],
            },
        ),
    ]
