# Generated by Django 4.2.30 on 2026-09-07 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("phishing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="phishingscan",
            name="url",
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
