# Generated by Django 4.2.30 on 2026-08-30 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ThreatNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "neo4j_id",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                (
                    "node_type",
                    models.CharField(
                        choices=[
                            ("ip", "IP Address"),
                            ("domain", "Domain"),
                            ("email", "Email Address"),
                            ("session", "Scan Session"),
                            ("actor", "Threat Actor"),
                        ],
                        max_length=16,
                    ),
                ),
                ("label", models.CharField(max_length=256)),
                ("risk_score", models.FloatField(default=0.0)),
                ("metadata", models.JSONField(default=dict)),
            ],
            options={
                "verbose_name": "Threat Node",
                "ordering": ["-risk_score", "-created_at"],
            },
        ),
    ]
