# Generated by Django 4.2.30 on 2026-08-30 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DeepfakeScanSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "session_id",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("is_deepfake", models.BooleanField(blank=True, null=True)),
                ("confidence", models.FloatField(blank=True, null=True)),
                ("frame_count", models.PositiveIntegerField(default=0)),
                ("processing_time_ms", models.FloatField(blank=True, null=True)),
                ("signed_verdict", models.TextField(blank=True, default="")),
                ("public_key_pem", models.TextField(blank=True, default="")),
            ],
            options={
                "verbose_name": "Deepfake Scan Session",
                "ordering": ["-created_at"],
            },
        ),
    ]
